# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20171124_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 24, 9, 39, 9, 835660)),
        ),
    ]
