# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171124_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('free_credits_used', models.CharField(blank=True, max_length=2, null=True)),
                ('paid_credits_used', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 12, 15, 41, 348232)),
        ),
    ]
