# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20180103_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 4, 9, 3, 21, 92392)),
        ),
    ]
