# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_details',
            name='company_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 20, 7, 17, 47, 29589)),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='email_guess',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='email_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_details',
            name='run_id',
            field=models.CharField(max_length=100),
        ),
    ]
