# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20171129_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 14, 12, 45, 5, 661976)),
        ),
    ]
