# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20171214_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_guest_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 18, 14, 28, 56, 483175)),
        ),
    ]
