# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20171218_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_details',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 18, 16, 22, 25, 516143)),
        ),
    ]
