# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='plan',
            field=models.CharField(default='plan', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='stripe_id',
            field=models.CharField(default='Stripe id', max_length=255),
        ),
    ]
