# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180105_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='stripe_id',
        ),
    ]
