# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180105_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=200)),
                ('amount', models.CharField(max_length=5)),
                ('date_time', models.DateTimeField()),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
        ),
    ]
