# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20180105_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytransactions',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 8, 4, 32, 982597)),
        ),
        migrations.AddField(
            model_name='sale',
            name='email_id',
            field=models.EmailField(default='Enter Email', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_name',
            field=models.CharField(default='username', max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='charge_id',
            field=models.CharField(default='stripe_id', max_length=32),
        ),
        migrations.DeleteModel(
            name='PayTransactions',
        ),
    ]
