# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20180105_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='emails_count',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 6, 10, 59, 39, 755511)),
        ),
    ]
