# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20180106_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 0, 24, 54, 406301)),
        ),
    ]
